import type { SeedSource } from '../media-opportunity-config';

/**
 * UK & Ireland source pack, for UKinbound (stand S5-220 at WTM 2026, co-exhibitors include
 * VisitBritain, VisitScotland, Visit Wales, Visit Kent, Visit West and Visit Jersey) and
 * usable for Tourism Ireland or any UK-wide body. The core seed set already carries the UK
 * trade titles (TTG, UKinbound, Tourism Alliance, GOV.UK VisitBritain); this pack adds
 * national and devolved-nation news, hospitality trade, and Irish national press.
 *
 * Every feed checked 6 October 2026 with the declared USER_AGENT and returned a current,
 * parseable document. Rejected: Travel Weekly and Travolution (feed returns 0 items), The
 * Caterer and Hospitality Ireland (404), Irish Times travel section (404), BreakingNews.ie
 * (410). Evening Standard and the Irish Times main feed parse but carry ~100 general items
 * each and were left out to keep the pool on-topic.
 */
export const UKIRELAND_SOURCES: SeedSource[] = [
  {
    id: 'bbc-uk',
    name: 'BBC News — UK',
    feedUrl: 'https://feeds.bbci.co.uk/news/uk/rss.xml',
    siteUrl: 'https://www.bbc.co.uk/news/uk',
    format: 'rss',
    verticals: ['dmo', 'charity', 'trade-body', 'education'],
    outletType: 'national-news',
    geographies: ['National (UK)'],
    region: 'UK & Ireland',
  },
  {
    id: 'bbc-business',
    name: 'BBC News — Business',
    feedUrl: 'https://feeds.bbci.co.uk/news/business/rss.xml',
    siteUrl: 'https://www.bbc.co.uk/news/business',
    format: 'rss',
    verticals: ['dmo', 'charity', 'trade-body', 'education'],
    outletType: 'national-news',
    geographies: ['National (UK)'],
    region: 'UK & Ireland',
  },
  {
    id: 'bbc-scotland',
    name: 'BBC News — Scotland',
    feedUrl: 'https://feeds.bbci.co.uk/news/scotland/rss.xml',
    siteUrl: 'https://www.bbc.co.uk/news/scotland',
    format: 'rss',
    verticals: ['dmo', 'charity', 'trade-body', 'education'],
    outletType: 'national-news',
    geographies: ['National (UK)', 'Regional'],
    region: 'UK & Ireland',
  },
  {
    id: 'bbc-wales',
    name: 'BBC News — Wales',
    feedUrl: 'https://feeds.bbci.co.uk/news/wales/rss.xml',
    siteUrl: 'https://www.bbc.co.uk/news/wales',
    format: 'rss',
    verticals: ['dmo', 'charity', 'trade-body', 'education'],
    outletType: 'national-news',
    geographies: ['National (UK)', 'Regional'],
    region: 'UK & Ireland',
  },
  {
    id: 'bbc-northern-ireland',
    name: 'BBC News — Northern Ireland',
    feedUrl: 'https://feeds.bbci.co.uk/news/northern_ireland/rss.xml',
    siteUrl: 'https://www.bbc.co.uk/news/northern_ireland',
    format: 'rss',
    verticals: ['dmo', 'charity', 'trade-body', 'education'],
    outletType: 'national-news',
    geographies: ['National (UK)', 'Regional'],
    region: 'UK & Ireland',
  },
  {
    id: 'belfast-live',
    name: 'Belfast Live',
    feedUrl: 'https://www.belfastlive.co.uk/news/?service=rss',
    siteUrl: 'https://www.belfastlive.co.uk',
    format: 'rss',
    verticals: ['dmo', 'charity', 'trade-body', 'education'],
    outletType: 'local-news',
    geographies: ['Regional', 'Local'],
    region: 'UK & Ireland',
  },
  {
    id: 'big-hospitality',
    name: 'BigHospitality',
    feedUrl: 'https://www.bighospitality.co.uk/arc/outboundfeeds/rss/',
    siteUrl: 'https://www.bighospitality.co.uk',
    format: 'rss',
    verticals: ['dmo', 'charity', 'trade-body', 'education'],
    outletType: 'trade',
    geographies: ['National (UK)'],
    region: 'UK & Ireland',
  },
  {
    id: 'hotel-owner',
    name: 'Hotel Owner',
    feedUrl: 'https://www.hotelowner.co.uk/feed/',
    siteUrl: 'https://www.hotelowner.co.uk',
    format: 'rss',
    verticals: ['dmo', 'charity', 'trade-body', 'education'],
    outletType: 'trade',
    geographies: ['National (UK)'],
    region: 'UK & Ireland',
  },
  {
    id: 'irish-independent',
    name: 'Irish Independent',
    feedUrl: 'https://www.independent.ie/rss/',
    siteUrl: 'https://www.independent.ie',
    format: 'rss',
    verticals: ['dmo', 'charity', 'trade-body', 'education'],
    outletType: 'national-news',
    geographies: ['Regional'],
    region: 'UK & Ireland',
  },
  {
    id: 'rte-news',
    name: 'RTÉ News',
    feedUrl: 'https://www.rte.ie/feeds/rss/?index=/news/',
    siteUrl: 'https://www.rte.ie/news',
    format: 'rss',
    verticals: ['dmo', 'charity', 'trade-body', 'education'],
    outletType: 'national-news',
    geographies: ['Regional'],
    region: 'UK & Ireland',
  },
  {
    id: 'irish-examiner',
    name: 'Irish Examiner',
    feedUrl: 'https://www.irishexaminer.com/feed/35-top_news.xml',
    siteUrl: 'https://www.irishexaminer.com',
    format: 'rss',
    verticals: ['dmo', 'charity', 'trade-body', 'education'],
    outletType: 'national-news',
    geographies: ['Regional'],
    region: 'UK & Ireland',
  },
  {
    id: 'thejournal-ie',
    name: 'TheJournal.ie',
    feedUrl: 'https://www.thejournal.ie/feed/',
    siteUrl: 'https://www.thejournal.ie',
    format: 'rss',
    verticals: ['dmo', 'charity', 'trade-body', 'education'],
    outletType: 'national-news',
    geographies: ['Regional'],
    region: 'UK & Ireland',
  },
];
